# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1be3a53dc70bbee82af46e2b83bca900d64a5e3191dfc8258fbfff6e3520fce86c7321a6609408934b220e6c9df537808eeaebc24cf5f671b66038d6da02eec0

test:
  secret_key_base: 79c0253c9854f792ed184c8c23c0fe78b5d561d88239c0bf16efbe346e17eaa0b2e552ef24d1d12342406aca4642ff3aefa2e59f821526d33f8ab2f0bfe874e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
